
stages:
  - lint
  - test
  - deploy

# Linting stage
lint:
  stage: lint
  image: python:3.8
  script:
    - pip install flake8
    - flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

# Testing stage (unit tests)
test:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - pytest --cov=src

# Deployment stage
deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install automl-model ./deployment/helm-chart --namespace default
  environment:
    name: production
  only:
    - master
